name: update-dev
on: push
#     branches:
#       - develop
jobs:
  build-and-deploy:
    runs-on: macos-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.18.0"
      - name: install deps
        run: yarn install
      - name: export
        run: yarn app expo export --public-url "$OTA_URL" --non-interactive
      - name: where am I ?
        run: ls
      - name: publish
        run: yarn app ota
