name: upgrade_major_release_prod
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: macos-latest
    environment: prod
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      FIREBASE_IOS_CLIENT_ID: ${{ secrets.FIREBASE_IOS_CLIENT_ID }}
      FIREBASE_IOS_REVERSED_CLIENT_ID: ${{ secrets.
      FIREBASE_IOS_API_KEY: ${{ secrets.FIREBASE_IOS_API_KEY }}
      FIREBASE_IOS_GCM_SENDER_ID: ${{ secrets.FIREBASE_IOS_GCM_SENDER_ID }}
      FIREBASE_IOS_PROJECT_ID: ${{ secrets.FIREBASE_IOS_PROJECT_ID }}
      FIREBASE_IOS_STORAGE_BUCKET: ${{ secrets.FIREBASE_IOS_STORAGE_BUCKET }}
      FIREBASE_IOS_GOOGLE_APP_ID: ${{ secrets.FIREBASE_IOS_GOOGLE_APP_ID }}
      APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      APPSTORE_KEY_CONTENT: ${{ secrets.APPSTORE_KEY_CONTENT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.18.0"
      - name: install deps
        run: |
          yarn install
          yarn app ios:pod
      - name: run fastlane
        run: fastlane prod
        working-directory: ./apps/app/ios
