name: create-major-release
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: install deps
        run: yarn install
      - name: run fastlane
        run: fastlane dev
        working-directory: ./apps/app/ios
